// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ManyServices.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Deltaban.Grpc {
  public static partial class SearchService
  {
    static readonly string __ServiceName = "GrpcBroker.SearchService";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Deltaban.Grpc.SearchRequest> __Marshaller_GrpcBroker_SearchRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Deltaban.Grpc.SearchRequest.Parser));
    static readonly grpc::Marshaller<global::Deltaban.Grpc.SearchResponse> __Marshaller_GrpcBroker_SearchResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Deltaban.Grpc.SearchResponse.Parser));

    static readonly grpc::Method<global::Deltaban.Grpc.SearchRequest, global::Deltaban.Grpc.SearchResponse> __Method_Search = new grpc::Method<global::Deltaban.Grpc.SearchRequest, global::Deltaban.Grpc.SearchResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "Search",
        __Marshaller_GrpcBroker_SearchRequest,
        __Marshaller_GrpcBroker_SearchResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Deltaban.Grpc.ManyServicesReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for SearchService</summary>
    public partial class SearchServiceClient : grpc::ClientBase<SearchServiceClient>
    {
      /// <summary>Creates a new client for SearchService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public SearchServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for SearchService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public SearchServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected SearchServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected SearchServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::Deltaban.Grpc.SearchResponse> Search(global::Deltaban.Grpc.SearchRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Search(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Deltaban.Grpc.SearchResponse> Search(global::Deltaban.Grpc.SearchRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_Search, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override SearchServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SearchServiceClient(configuration);
      }
    }

  }
}
#endregion
