// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Sum.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace MyGrpc {
  public static partial class SumService
  {
    static readonly string __ServiceName = "MyGrpcPackage.SumService";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::MyGrpc.SumRequest> __Marshaller_MyGrpcPackage_SumRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::MyGrpc.SumRequest.Parser));
    static readonly grpc::Marshaller<global::MyGrpc.SumResponse> __Marshaller_MyGrpcPackage_SumResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::MyGrpc.SumResponse.Parser));

    static readonly grpc::Method<global::MyGrpc.SumRequest, global::MyGrpc.SumResponse> __Method_CalculateSum = new grpc::Method<global::MyGrpc.SumRequest, global::MyGrpc.SumResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CalculateSum",
        __Marshaller_MyGrpcPackage_SumRequest,
        __Marshaller_MyGrpcPackage_SumResponse);

    static readonly grpc::Method<global::MyGrpc.SumRequest, global::MyGrpc.SumResponse> __Method_CalculateManyTimeSum = new grpc::Method<global::MyGrpc.SumRequest, global::MyGrpc.SumResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "CalculateManyTimeSum",
        __Marshaller_MyGrpcPackage_SumRequest,
        __Marshaller_MyGrpcPackage_SumResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::MyGrpc.SumReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for SumService</summary>
    public partial class SumServiceClient : grpc::ClientBase<SumServiceClient>
    {
      /// <summary>Creates a new client for SumService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public SumServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for SumService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public SumServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected SumServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected SumServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::MyGrpc.SumResponse CalculateSum(global::MyGrpc.SumRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CalculateSum(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::MyGrpc.SumResponse CalculateSum(global::MyGrpc.SumRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CalculateSum, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::MyGrpc.SumResponse> CalculateSumAsync(global::MyGrpc.SumRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CalculateSumAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::MyGrpc.SumResponse> CalculateSumAsync(global::MyGrpc.SumRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CalculateSum, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::MyGrpc.SumResponse> CalculateManyTimeSum(global::MyGrpc.SumRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CalculateManyTimeSum(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::MyGrpc.SumResponse> CalculateManyTimeSum(global::MyGrpc.SumRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_CalculateManyTimeSum, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override SumServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SumServiceClient(configuration);
      }
    }

  }
}
#endregion
