// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Sum.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace MyGrpc {
  public static partial class SumService
  {
    static readonly string __ServiceName = "MyGrpcPackage.SumService";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::MyGrpc.SumRequest> __Marshaller_MyGrpcPackage_SumRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::MyGrpc.SumRequest.Parser));
    static readonly grpc::Marshaller<global::MyGrpc.SumResponse> __Marshaller_MyGrpcPackage_SumResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::MyGrpc.SumResponse.Parser));

    static readonly grpc::Method<global::MyGrpc.SumRequest, global::MyGrpc.SumResponse> __Method_CalculateSum = new grpc::Method<global::MyGrpc.SumRequest, global::MyGrpc.SumResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CalculateSum",
        __Marshaller_MyGrpcPackage_SumRequest,
        __Marshaller_MyGrpcPackage_SumResponse);

    static readonly grpc::Method<global::MyGrpc.SumRequest, global::MyGrpc.SumResponse> __Method_CalculateManyTimeSum = new grpc::Method<global::MyGrpc.SumRequest, global::MyGrpc.SumResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "CalculateManyTimeSum",
        __Marshaller_MyGrpcPackage_SumRequest,
        __Marshaller_MyGrpcPackage_SumResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::MyGrpc.SumReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of SumService</summary>
    [grpc::BindServiceMethod(typeof(SumService), "BindService")]
    public abstract partial class SumServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::MyGrpc.SumResponse> CalculateSum(global::MyGrpc.SumRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task CalculateManyTimeSum(global::MyGrpc.SumRequest request, grpc::IServerStreamWriter<global::MyGrpc.SumResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(SumServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CalculateSum, serviceImpl.CalculateSum)
          .AddMethod(__Method_CalculateManyTimeSum, serviceImpl.CalculateManyTimeSum).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, SumServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CalculateSum, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::MyGrpc.SumRequest, global::MyGrpc.SumResponse>(serviceImpl.CalculateSum));
      serviceBinder.AddMethod(__Method_CalculateManyTimeSum, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::MyGrpc.SumRequest, global::MyGrpc.SumResponse>(serviceImpl.CalculateManyTimeSum));
    }

  }
}
#endregion
